name: continuos integrtion

on:

  pull request:
    types:[opened,synchronize]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
        uses: actions/checkout@v3
    - name: Comando
      run: "echo 'ola,pessoas'"
    - name: Comando
      run: "npm run lint"